language: perl

os:
    - linux
    - osx

env:
    - BACKEND=moar
    - BACKEND=jvm

matrix:
    allow_failures:
        - env: BACKEND=jvm
    fast_finish: true

sudo: false

before_install:
    - 'if [[ $BACKEND == "moar" ]]; then export VM_OPTS="--gen-moar"; fi'
    - git clone https://github.com/rakudo/rakudo.git $HOME/rakudo
    - cd $HOME/rakudo
    - perl Configure.pl $VM_OPTS --gen-nqp --backends=$BACKEND
    - make install
    - export PATH=$HOME/rakudo/install/bin:$PATH
    - export PATH=$HOME/rakudo/install/share/perl6/site/bin:$PATH

    - git clone https://github.com/ugexe/zef $HOME/zef
    - cd $HOME/zef
    - perl6 -Ilib bin/zef install .

    - cd $TRAVIS_BUILD_DIR

install:
    - perl6 -v
    - zef --depsonly install .

script:
    - prove -v -e 'perl6 -Ilib' t/
